name: Continuous Integration
on:
    push:
        branches:
          - main
    pull_request:
        types: 
          - opened
          - reopened
          - synchronize
          - ready_for_review
        branches:
          - main

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

          - name: Use Node.js
            uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
            with:
                node-version: 18.x

          - name: Cache node_modules
            id: cache-npm-packages
            uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
            env:
              cache-name: cache-node_modules
            with:
              path: node_modules
              key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

          - name: Install Dependencies
            if: ${{ steps.cache-npm-packages.outputs.cache-hit != 'true' }}
            run: npm ci

          - name: Build
            run: npm run build

          - name: Setup Pages
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            uses: actions/configure-pages@b8130d9ab958b325bbde9786d62f2c97a9885a0e # v3.0.7

          - name: Upload artifact
            uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
            with:
                path: '.vitepress/dist'

          - name: Deploy to GitHub Pages
            id: deployment
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            uses: actions/deploy-pages@de14547edc9944350dc0481aa5b7afb08e75f254 # v2.0.5
